Colin-b/pytest_httpx

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_mock.py
tests/test_httpx_sync.py
tests/test_mock.py

- Allow to provide JSON response as python values.
- Mock async httpx requests as well.
- Allow to provide files and boundary for multipart response.
- Allow to provide data as a dictionary for multipart response.
- Allow to provide callbacks that are executed upon reception of a request.
- Handle the fact that parameters may be introduced in httpx *Dispatcher.send method.
- Allow to retrieve all matching requests with HTTPXMock.get_requests
- method can now be provided even if not entirely upper cased.
- content parameter renamed into data.
- HTTPXMock.get_request now fails if more than one request match. Use HTTPXMock.get_request instead.
- HTTPXMock.requests is now private, use HTTPXMock.get_requests instead.
- HTTPXMock.responses is now private, it should not be accessed anyway.
- url …

Release 0.0.3

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py
tests/test_mock.py

- url is not a mandatory parameter for response registration anymore.
- url is not a mandatory parameter for callback registration anymore.
- url is not a mandatory parameter for request retrieval anymore.
- method does not have a default value for response registration anymore.
- method does not have a default value for callback registration anymore.
- method does not have a default value for request retrieval anymore.
- url and methods are not positional arguments anymore.

Release 0.0.4

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py
tests/test_plugin.py

- requires [`pytest`](https://docs.pytest.org/en/latest/) 6.
- `assert_and_reset` mock method has been renamed to `reset` and now takes a boolean parameter to specify if assertion should be performed.
- It is now possible to disable the assertion that all registered responses were requested thanks to the `assert_all_responses_were_requested` fixture. Refer to documentation for more details. (fixes #15 )
- It is not possible to provide an URL encoded response anymore by providing a dictionary in `data` parameter.

Release 0.5.0

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Requires [`httpx`](https://www.python-httpx.org)==0.14.*

Release 0.6.0

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_plugin.py

- `non_mocked_hosts` fixture allowing to avoid mocking requests sent on some specific hosts. Closes #28 
- Display the matchers that were not matched instead of the responses that were not sent.

Release 0.8.0

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Requires [`httpx`](https://www.python-httpx.org)==0.15.*
- Callbacks are now called with `ext` dictionary instead of `timeout`. To follow `httpcore` design changes. You can still retrieve timeout by using ```ext['timeout']```

Release 0.9.0

---

CHANGELOG.md
README.md
pytest_httpx/version.py
setup.py

- Requires [`httpx`](https://www.python-httpx.org)==0.17.\*

Release 0.11.0

---

.travis.yml
CHANGELOG.md
LICENSE
README.md
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Requires [`httpx`](https://www.python-httpx.org)==0.18.\*
- `ext` callback parameter was renamed into `extensions`.

Release 0.12.0

---

setup.py

Currently, importing `pytest_httpx` causes `mypy` errors because no type information is packaged:
```
main.py:1: error: Skipping analyzing "pytest_httpx": found module but no type hints or library stubs
main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
This PR includes a `py.typed` file so that `mypy` knows to read the annotations directly from the package source files.
My test functions are fully annotated so importing is necessary, e.g.
```python
from httpx_mock import HTTPXMock
def test_something(httpx_mock: HTTPXMock) -> None:
...
```
[Relevant section of PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information).

Add py.typed to distribute typing information per PEP 561

---

CHANGELOG.md
README.md
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Requires [`httpx`](https://www.python-httpx.org)==0.19.\*
- `files` parameter of `httpx_mock.add_response` now expect dictionary values to be binary (as per [httpx new requirement](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0190-19th-june-2021)).

Release 0.13.0

---

pytest_httpx/__init__.py

This addresses the mypy error:
```
error: Module "pytest_httpx" does not explicitly export attribute "HTTPXMock"; implicit reexport disabled  [attr-defined]
```

Explicitly export `HTTPXMock`, `to_response`, etc. to appease `mypy --strict`

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Do not consider a response as read, even if it is not a stream, before returning to `httpx`. Allowing any specific httpx handling to be triggered such as `httpx.Response.elapsed` computing.

Release 0.17.1

---

CHANGELOG.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Do not consider a callback response as read, even if it is not a stream, before returning to `httpx`. Allowing any specific httpx handling to be triggered such as `httpx.Response.elapsed` computing.

Release 0.17.2

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- A callback can now raise an exception again (regression in mypy check since [0.16.0]).
- An exception can now be raised without creating a callback by using `httpx_mock.add_exception` method.

Release 0.17.3

---

CHANGELOG.md
LICENSE
README.md
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Callback are now executed as expected when there is a matching already sent response.
- Registration order is now looking at responses and callbacks. Prior to this version, registration order was looking at responses before callbacks.
- `httpx_mock.add_response` `data`, `files` and `boundary` parameters have been removed. It was deprecated since `0.17.0`. Refer to this version changelog entry for more details on how to update your code.

Release 0.18.0

---

.github/workflows/test.yml
pytest_httpx/version.py
setup.py

Pytest just released [Pytest v7](https://pypi.org/project/pytest/).  I'm trying to upgrade a project of mine to use it by pytest-httpx has a dependency on `pytest==6.*` which stops me from using v7 in my project.
* Update Github Actions to test against Pytest v6 and v7
* Loosen install requirements to allow v6 and v7
IMO It's safe to use `pytest>=6.*` as the version specifier as Pytest follow long deprecation periods and don't often break existing code that is widely used, even in major version releases. I'm happy to switch this to `pytest>=6.*,<8.0` if you prefer

Support pytest v7

---

.github/workflows/test.yml
CHANGELOG.md
setup.py

- Add support for [`pytest`](https://docs.pytest.org)==7.\* ([`pytest`](https://docs.pytest.org)==6.\* is still supported for now).  (many thanks to [`Craig Blaszczyk`](https://github.com/jakul))

Release 0.20.0

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
README.md
pytest_httpx/version.py
setup.py

- Requires [`httpx`](https://www.python-httpx.org)==0.23.\*
- Python 3.6 is no longer supported.

Release 0.21.0

---

.pre-commit-config.yaml
CHANGELOG.md
CONTRIBUTING.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- URL containing non ASCII characters in query can now be matched.
- Requests are now cleared when calling `httpx_mock.reset`.
fixes #82
fixes #87

Release 0.21.2

---

CHANGELOG.md
setup.py

Python packaging 23.0 removes the ability to use inequalities with specifiers containing `*`. This means that projects that depend on this library fail to build if using an updated build tooling.
See the following:
- https://github.com/pdm-project/pdm/issues/1596
- https://github.com/pdm-project/pdm/issues/1619
- https://github.com/mkaranasou/pyaml_env/issues/30

Update version specifiers for pytest

---

.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
pytest_httpx/version.py
setup.py

- Update version specifiers for `pytest` dependency to support `packaging` `23`.
- Add explicit support for `python` `3.11`.

Release 0.21.3

---

MANIFEST.in

Include `CHANGELOG.md` and `tests` directory in generated sdist archives.  This will help Linux distributions and Conda to package pytest-httpx without having to resort to generated GitHub snapshots.

Include CHANGELOG and tests in sdist

---

.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
MANIFEST.in
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
setup.py

- Python `3.7` and `3.8` are no longer supported.
- `httpx_mock.add_response` is now returning a new `httpx.Response` instance upon each matching request. Preventing unnecessary cascading streams.
Closes #99

Release 0.23.0

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Version `0.23.0` introduced a regression removing the support for mutating json content provided in `httpx_mock.add_response`. 
- This is fixed, you can now expect the JSON return being as it was when provided to `httpx_mock.add_response`:
```python
mutating_json = {"content": "request 1"}
httpx_mock.add_response(json=mutating_json)
mutating_json["content"] = "request 2"
httpx_mock.add_response(json=mutating_json)
```

Release 0.23.1

---

CHANGELOG.md
pytest_httpx/_httpx_mock.py

closes #104 
Adding `:Any` type hint to `**matchers` arguments. This is to satisfy pyrights strict type checking mode.

Add Any type to **matchers argument to statisfy strict type checking

---

CHANGELOG.md
pytest_httpx/_httpx_mock.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

closes #106 
Make sure we still display the original header name and value in errors if httpx converted a header name to lower case, and another parameter doesn't match. 
So we display
```python
httpx.TimeoutException: No response can be found for GET request on http://www.google.com with {'MyHeader': 'Something'} headers amongst:
E       Match GET requests on http://www.google.com?q=b with {'MyHeader': 'Something'} headers
```
instead of 
```python
httpx.TimeoutException: No response can be found for GET request on http://www.google.com with {} headers amongst:
E       Match GET requests on http://www.google.com?q=b with {'MyHeader': 'Something'} headers
```
with this test:
```python
from pytest_httpx import HTTPXMock
import httpx
def test_something(httpx_mock: HTTPXMock): …
```

Make sure the match_headers errors are displayed correctly for lower cased version

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

closes #83 
Added the match_json_content matcher which checks if the passed object matches the json decoded request body
I preferred adding a new matcher `match_json_content` over modifying the existing `match_content`.
I could have added conditions that if the `match_content` argument isn't of type `bytes` then assume we want to json decode the body, but that doesn't match nicely with [Explicit is better than implicit.](https://peps.python.org/pep-0020/), and with the extra argument I think the code also stays cleaner.

Added the match_json_content matcher

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Requires [`httpx`](https://www.python-httpx.org)==0.25.\*
- `pytest` `6` is no longer supported.

Release 0.25.0

---

CHANGELOG.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/_request_matcher.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

Handle custom transport

---

.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/_pretty_print.py
pytest_httpx/_request_matcher.py
pytest_httpx/version.py
setup.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- Explicit support for python `3.12`.
- Custom HTTP transport are now handled (parent call to `handle_async_request` or `handle_request`).
- Only HTTP transport are now mocked, this should not have any impact, however if it does, please feel free to open an issue describing your use case.

Release 0.27.0

---

.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
LICENSE
pytest_httpx/version.py

- Add support for [`pytest`](https://docs.pytest.org)==8.\* ([`pytest`](https://docs.pytest.org)==7.\* is still supported for now).  (many thanks to [`Yossi Rozantsev`](https://github.com/Apakottur))

Release 0.29.0

---

pyproject.toml
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/_pretty_print.py
pytest_httpx/_request_matcher.py

Filter all the code over `pyupgrade --py38`.

really drop python<=3.8 support

---

pyproject.toml

The `[tool.setuptools.packages.find]` section in `pyproject.toml` was removed because it didn't affect the generated wheel, as the wheel still excluded the `tests` directory with this section removed.
Including `[tool.setuptools.packages.find]` caused issues with multiple builds of the package. This led to the creation of infinite nested `build/lib/build/lib` directories. By removing this section, the default behaviour now ignores 'build*' directories, preventing these problems.
For more details, refer to the related discussion on the setuptools: https://github.com/pypa/setuptools/issues/4076

Bug fix to allow multiple builds of package

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
tests/test_plugin.py

Resolves #137
We want to be able to configure how the `httpx_mock` fixture behaves at different scopes. A pytest marker can be used at module, class, or test scope and so is what is used here.
Providing a non-default value from the fixtures will emit a DeprecationWarning for each test with the exact marker it can be replaced with:
```
=================================== warnings summary ===================================
tests/test_tmp.py::test_a
tests/test_tmp.py::test_b
/.../pytest_httpx/__init__.py:56: DeprecationWarning: The assert_all_responses_were_requested and non_mocked_hosts fixtures are deprecated.
Use the following marker instead:
pytest.mark.httpx_mock(assert_all_responses_were_requested=False)
warnings.warn(
tests/test_tmp.py::test_c
/.../pytest_httpx/__init__.py:56: …
```

Setup httpx_mock via marker instead of fixtures

---

CHANGELOG.md
README.md
pytest_httpx/_httpx_mock.py
pytest_httpx/_request_matcher.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

- It is now possible to match on content provided as async iterable by the client.
@fixes #148

Release 0.31.1

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
pytest_httpx/version.py
tests/test_plugin.py

- `httpx_mock` marker can now be defined at different levels for a single test.
@fixes #154
@fixed #155

Release 0.31.2

---

CHANGELOG.md
README.md
pytest_httpx/__init__.py
pytest_httpx/_httpx_internals.py
pytest_httpx/_httpx_mock.py
pytest_httpx/_options.py
pytest_httpx/_request_matcher.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py
tests/test_plugin.py

- The following option is now available:
- `can_send_already_matched_responses` (boolean), defaulting to `False`.
- Assertion failure message in case of unmatched responses is now linking documentation on how to deactivate the check.
- Assertion failure message in case of unmatched requests is now linking documentation on how to deactivate the check.
- Documentation now clearly state the risks associated with changing the default options.
- Assertion failure message in case of unmatched requests at teardown is now describing requests in a more user-friendly way.
- Assertion failure message in case of unmatched requests at teardown is now prefixing requests with `- ` to highlight the fact that this is a list, preventing misapprehension in case only one element exists.
- Assertion failure …

Release 0.32.0

---

.github/workflows/release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
README.md
pyproject.toml
pytest_httpx/__init__.py
pytest_httpx/_httpx_mock.py
pytest_httpx/_options.py
pytest_httpx/_pretty_print.py
pytest_httpx/_request_matcher.py
pytest_httpx/version.py
tests/test_httpx_async.py
tests/test_httpx_sync.py
tests/test_plugin.py

- Explicit support for python `3.13`.
- `should_mock` option (callable returning a boolean) is now available, defaulting to always returning `True`. Refer to documentation for more details.
- Matching on the full multipart body can now be performed using `match_files` and `match_data` parameters. Refer to documentation for more details.
- Matching on extensions (including timeout) can now be performed using `match_extensions` parameter. Refer to documentation for more details.
- `non_mocked_hosts` option is not available anymore. Use `should_mock` instead as in the following sample:
```python
import pytest
@pytest.mark.httpx_mock(non_mocked_hosts=["my_local_test_host"])
def test_previous_behavior(httpx_mock):
...
@pytest.mark.httpx_mock(should_mock=lambda request: request.url.host not in …
```

Release 0.33.0

---

pytest_httpx/_httpx_mock.py
pytest_httpx/_request_matcher.py
tests/test_httpx_async.py
tests/test_httpx_sync.py

Hi,
In my company we've have a case where we want to match one parameter of query string and ignore others, right now this is only possible via regex as using `httpx.URL(..., params = ...)` will convert all the `params` to strings, so if we pass something like `{"a": 1, "b": ANY}` we get`{"a": 1, "b": "<ANY>"}`, that does not get matched.
So this PR is adding support for extra keyword argument `match_params` allowing to pass them directly

feat: add support for `match_params` allowing partial params matching
